# Generated by Django 2.2.2 on 2019-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10, verbose_name='商品编号')),
                ('product_name', models.CharField(max_length=256, verbose_name='商品名称')),
                ('product_class', models.CharField(max_length=25, verbose_name='商品类别')),
                ('product_price', models.CharField(max_length=20, verbose_name='商品价格')),
                ('product_url', models.CharField(max_length=20, verbose_name='商品链接')),
            ],
            options={
                'verbose_name': '推荐商品信息',
            },
        ),
    ]
